name: A simple Docker action
 
on:
  issues:
    types: [opened, edited, labeled]
 
jobs:
  user-and-time:
    runs-on: ubuntu-latest
    name: Running a simple BASH script
    steps:
    - name: A simple BASH script
      id: BASH
      uses: melscoop-test/ACC_05-PG7-DKRTest
